### ISSUE TITLE
addon does not seem to like hyper-v

### ISSUE THREAD

**Issue by gurkburk76** [snowzach/doods#11]
19-11-27 13:54:09 ERROR (SyncWorker_28) [hassio.docker] Can't start addon_d5f40609_doods: 500 Server Error: Internal Server Error ("linux runtime spec devices: error gathering device information while adding custom device "/dev/bus/usb": no such file or directory")

When i run it under hyper-v, it seems to work fine under virtualbox.

**Comment by DanielWinks** [comment]
Hyper-V does not support USB device passthrough. You'll need to run it under VirtualBox, KVM, ESXi or any other platform that provides USB support.

**Comment by gurkburk76** [comment]
No workaround possible? I'm not planning in using any usb accelerator or other device so no real need for usb support.
moving to a new vm platform with usb support *just* for this addon is not feasible for me.

**Comment by snowzach** [comment]
Are you running it with docker compose? remove the `devices:` section from the docker compose file.

**Comment by gurkburk76** [comment]
> 
> 
> Are you running it with docker compose? remove the `devices:` section from the docker compose file.

Running hass.io.

**Comment by snowzach** [comment]
Hm, I am not sure how to fix this without creating a whole other repository.

**Comment by DanielWinks** [comment]
The HassIO add-on uses a devices section to allow for Google Coral USB accelerators, here: https://github.com/snowzach/hassio-addons/blob/master/doods/config.json

The real fix is not using Hyper-V as there's many other issues using it with Home Assistant. Or not using HassIO and instead using regular Home Assistant Docker images with Docker Compose and leaving out the devices section. Maintaining two HassIO add-ons just to accommodate a very small population of Hyper-V users seems like it would just confuse the general HassIO user base.

**Comment by snowzach** [comment]
FWIW, I did open an issue on Hass.IO and at least asked how it might be possible to customize this during the config phase by the user. https://github.com/home-assistant/hassio/issues/1389

Really, the issues belongs in this repository. https://github.com/snowzach/hassio-addons

You can fork that repository and edit the doods/config.json file and remove the `devices` section and add it as your own repository and it should work. It sounds like Hyper-V is not very HASS friendly though.

**Comment by DanielWinks** [comment]
> It sounds like Hyper-V is not very HASS friendly though.

It's just that Hyper-V has zero ability to use USB devices. HassIO (well, Home Assistant in general) uses USB for quite a number of things, Coral devices for TF, and USB Z-wave and ZigBee radios are the the biggest examples, but even things like adding Bluetooth or, well, anything else that uses USB. Proxmox works really well, or if you have a need to run Windows as the base OS, VirtualBox allows USB pass-through and works well too. It's a shame, really, since otherwise Hyper-V is a quite good hypervisor.

**Comment by gurkburk76** [comment]
Yeah hyper-v hasen't really given me problems, except for this usb problem really ;)
proxmox seems fine and all, the reason it's not "easy" to switch from server 2016 to proxmox is the many tb's i have as reFS on there in storage spaces, If i happen to find some more storage space to move stuff back and forth i might setup proxmox with zfs and go with that.

A bit off topic, sorry :)

Otoh, if this issues ultmately leads to being able to customize this during the config phase by the user home-assistant/hassio#1389 that would possibly benefit more ppl, so that's a win.

**Comment by snowzach** [comment]
FWIW, I have a pretty good size home lab but I still run Hass on a raspberry pi. If I'm working on my server, all the home automations still work. :-)

**Comment by snowzach** [comment]
I'm going to close this one for now.
