### ISSUE TITLE
Add support for image detection models with only a score output

### ISSUE THREAD

**Issue by snowzach** [snowzach/doods#12]
Add support for object detection models that only return a score. This should return the confidence with the entire image selected [0,0,1,1] for the bounding match box.

**Comment by snowzach** [comment]
@r1cht3r are you able to give me a hint to what the output of that racoon model is? It just shows that it outputs 1 tensor that's uint8 and 5 bytes. I can't seem to figure out how to decode it.

**Comment by r1cht3r** [comment]
Here's the `tflite_metadata.json` that was provided with the tflite file from GCP, looks like just scores are outputted. Could the `supportedTfVersions` be an issue?
```
{
    "batchSize": 1, 
    "imageChannels": 3, 
    "imageHeight": 224, 
    "imageWidth": 224, 
    "inferenceType": "QUANTIZED_UINT8", 
    "inputTensor": "image", 
    "inputType": "QUANTIZED_UINT8", 
    "outputTensor": "scores", 
    "supportedTfVersions": [
        "1.10", 
        "1.11", 
        "1.12", 
        "1.13"
    ]
}
```

**Comment by snowzach** [comment]
Okay, I added support for this model type. This one doesn't actually provide boxes, it just provides a match percentage for every label.

**Comment by jasonramey** [comment]
@snowzach working great here, thank you!
