### ISSUE TITLE
File Output

### ISSUE THREAD

**Issue by iRanduMi** [snowzach/doods#15]
I'm able to utilize DOODS within hass.io, however, I'd prefer to utilize the docker directly to provide more flexibility.  The hass.io implementation provides the ability to output the file to a local directory and it works great.  I don't seem to see any documentation on how to complete this via an API call to the docker container.

**Comment by iRanduMi** [comment]
Just following up on this to verify if there is the ability to output the saved snapshot with the objects identified (Example: Car - 25%).  Thank you!

**Comment by snowzach** [comment]
The API/Docker Image only provides image detection information in the form of returned JSON about what was detected and where it is in the image. It's not able to write any images. The doods component that is part of Home Assistant is the piece that gets that data and then draws the boxes on the image and writes it to disk. 

You will need to write a client that writes out files if you wish to do this. DOODS is only meant to be an API that's used by other software.
