### ISSUE TITLE
add other models

### ISSUE THREAD

**Issue by lenny76** [snowzach/doods#18]
hi,
do you plan to add other models?

**Comment by snowzach** [comment]
You can add any model you like. I may add inception v2 as a default model though.

**Comment by lenny76** [comment]
well, I'm new in this world, so any instruction to add them would be nice 👯‍♀️

**Comment by snowzach** [comment]
It really depends on your platform. How are you using it?

**Comment by lenny76** [comment]
i'm experimenting a nodejs server with webclient that downloads a webcam snapshot and gives it to doods for person recognition

**Comment by snowzach** [comment]
If you look in the README.md it shows you how to run it with docker. The `fetch_models.sh` script will download 3 models and creates and example.yaml config file and shows you the docker command to run it with those options. Let me know if that isn't clear and I  can try to help a little more.

**Comment by snowzach** [comment]
Okay, I now include the inception model by default. It's under the detector called `tensorflow`
