### ISSUE TITLE
Makefile errors on local machine

### ISSUE THREAD

**Issue by peterk-code** [snowzach/doods#19]
Build script tries to build Dockerfile.builder.${CONFIG} but there is only a single Dockerfile.builder without processor-specific extension

Docker files reference registry.prozach.org instead of local repo for built images

**Comment by snowzach** [comment]
I am working on this.... Check out the rebuild branch...

**Comment by snowzach** [comment]
@peterk-code look at the latest version. You should be able to just run `make docker` and it will create an image call `snowzach/doods:local`
