### ISSUE TITLE
TensorFlow 2...

### ISSUE THREAD

**Issue by MYeager1967** [snowzach/doods#31]
Any plans to update DOODS with TensorFlow2?

**Comment by snowzach** [comment]
It's on a specific commit to support the EdgeTPU.. but I believe it is a Tensorflow 2 codebase already.

**Comment by MYeager1967** [comment]
You'd be the one to know as you probably it it together. I understood it was still the older version. I'd love a full tensorflow engine using the edgeTPU though....

**Comment by snowzach** [comment]
I don't think that's going to happen with the EdgeTPU. There's a GPU version already of DOODS for tensorflow if you have an Nvidia card that supports tensorflow.

**Comment by MYeager1967** [comment]
Yeah, unfortunately I'm not using a machine with an add-on video card. Don't plan to make that change either. I have no idea what the difference is in the code and unless the people writing the code decide to make it an option, I realize it won't happen. But it would be nice. The tflite accuracy just left a lot to be desired. Maybe with the EdgeTPU it's better. 

 I know you're busy, and I have no idea what your future plans are for DOODS, but I appreciate your efforts so far. I've tried a few other methods of object detection, and I keep coming back. Please continue to improve and support this...
