### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by depuits** [snowzach/doods#34]
Would it be possible to add support for Cross-Origin Resource Sharing. This way you would be able to call the API directly from a website.

**Comment by snowzach** [comment]
Okay... I tried adding it.. give it a shot and let me know.

**Comment by depuits** [comment]
Thx it's working, I thought you would have added it as on option or config, but it works like this. Now my [visualizer](https://gist.github.com/depuits/000cbc6c8bbf064a710e95ae062bf91b) works locally without the need for another backend relay server.

**Comment by snowzach** [comment]
It is a config option. I just made it default to pretty open. Glad it worked. Super cool idea.
