### ISSUE TITLE
Sequence analyse 

### ISSUE THREAD

**Issue by alekslyse** [snowzach/doods#36]
Is it possible to analyse a sequence of frames with doods and end up with an average. I raised the same question about another system, but I see the dilemma of for example a door opens, doods triggers and see nothing, but a person show up 2 seconds later. It would be great if doods could recheck / analyse x frames so it does not miss a close event like a person exists a car or door. Same with the car today it would just trigger about the car, but if it checked some more frames it would detect the car and the person exit it

**Comment by snowzach** [comment]
DOODS only checks frames. It's whatever you are using to send DOODS frames. What really needs modified is whatever is sending DOODS frames. (Home assistant?)

**Comment by snowzach** [comment]
I am going to close this one. I want to eventually create a service that sits in front of Doods and does what you are talking about.
