### ISSUE TITLE
Installing libedgetpu from apt-get 

### ISSUE THREAD

**Issue by zewelor** [snowzach/doods#4]
Hi

first thanks for great software. I've saw you updated dockerfile build pipeline, using downloading libedgetpu via curl. Not sure if you saw, its now properly packed in deb packages, maybe it will simplify build pipeline and images: https://coral.withgoogle.com/docs/accelerator/get-started/#1-install-the-edge-tpu-runtime . Feel free to close it.

**Comment by snowzach** [comment]
Thanks for the suggestion. It's nice to see them putting in work to make the library easier to use. It's much easier with r1.15. Doods really only needs one file (the library) from the package. It's sorta convoluted how it creates packages for different architectures. It's probably going to be more straight forward to get it from curl. Thanks for the suggestion though.
