### ISSUE TITLE
Question: Can you make it detect specific people?

### ISSUE THREAD

**Issue by LordNex** [snowzach/doods#41]
I was wondering if you could have it compare the image to a small set of "known" people for recognition. For instance if I have an image of me and each of my family members, if it sees a person detection and it matches 90% correct then it tests those images agains the known images to see if any match, then report back?  Would make it so that we could trigger automations based upon specific recognitions

**Comment by snowzach** [comment]
It can be done.. but you need to train a model. DOODS just operates on models. You need to look into how to train a custom model.
