### ISSUE TITLE
Support for Older nVidia GPU?

### ISSUE THREAD

**Issue by ahmadnbl** [snowzach/doods#48]
Currently I have laptop with these specs:
- Lenovo G400s
- 8GB Ram
- i3 3110-M
- nVidia GT 720M

Software specs:
- Host Debian buster
- Installed nvidia container
- nVidia driver using 390.xx version
- Installed Cuda version: 9.1.85

When I run the docker image, I got this error
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: requirement error: unsatisfied condition: cuda>=10.2, please update your driver to a newer version, or use an earlier cuda container\\\\n\\\"\"": unknown.
ERRO[0003] error waiting for container: context canceled
```
It stated that I need to install newer driver and Cuda version, which I can't because the gpu is not supported anymore on newer driver version.

For that, I just wanna ask, do you have any plan to support older nVidia GPU?

**Comment by snowzach** [comment]
I had a horrible time getting nvidia to work.. I probably won't spend a lot of time trying to backport it. That's a pretty old card. If you know docker, feel free to try to modify Dockerfile.cuda to see if you can get an older version to work.

**Comment by ahmadnbl** [comment]
Haha ok then, will try to custom the docker image. Will inform in this thread if I got any update.
For now, will closed this ticket first. Thanks!
