### ISSUE TITLE
How can I be sure that my Coral Google USB is being used?

### ISSUE THREAD

**Issue by mmatesic01** [snowzach/doods#49]
Hello,

I am running this on Raspbery OS Lite on Rpi4 4GB.
Coral Google USB is recognized with "lsusb"
I have edited congif.yaml in my "deafult" detector to "hwaccel: True".
Coral Google USB is warm, but is there way to check in SW that it is being used intstead of RPi CPU?
My "process_time" each 2s is between 0,35 s to 0,45 s ( grabbing from rtsp source 1080p 15fps)

Thanks.

**Comment by snowzach** [comment]
You need to use a model that supports the edgetpu. (Pretty much every model that supports the edgetpu will have edgetpu in the filename)

**Comment by mmatesic01** [comment]
I did that and now is OK. Thanks.
