### ISSUE TITLE
mqtt support

### ISSUE THREAD

**Issue by johntdyer** [snowzach/doods#5]
any thoughts on adding mqtt support, kinda like how frigate does it ?

**Comment by snowzach** [comment]
Not to DOODS. It's meant just to be a simple API that does the object detection only. With that said, I was thinking about writing my own system that does detection/mqtt/etc like frigate that leverages DOODS. It would probably be somewhat trivial to add DOODS support to frigate as well.  

The next thing I am working on is writing an RTSP proxy so I can mux feeds out of my cameras to BlueIris and Home assistant and whatever this detection engine I write next is.
