### ISSUE TITLE
Jetson Nano Support

### ISSUE THREAD

**Issue by meteosat007** [snowzach/doods#50]
I have run the docker cuda variant but get errors infering that the aarch64 on the Nano is not supported.

Please could you confirm if in fact the DOODS will run on Nano using the inbuilt GPU?

Thnaks

**Comment by snowzach** [comment]
I know it will but the cuda variant is currently for x86 only. I think someone forked it and made one for jetson but I can't remember who it was. Maybe comb through the forks.

**Comment by llego** [comment]
Hi @meteosat007 , I managed to get it up an running using the information in [the comments of this issue](https://github.com/snowzach/doods/issues/25#issuecomment-750016888).

**Comment by meteosat007** [comment]
Hi llego,

Do you have a few more steps of detail as I have cloned the repo, altered the detector file and I think a step exists befor the docker-compose?

**Comment by llego** [comment]
You also need to build your own image using the dockerfile in @sakalauskas's [first post](https://github.com/snowzach/doods/issues/25#issue-642639325) in the thread. He describes the steps in the post.
