### ISSUE TITLE
Overlapping/Redundant Identifications

### ISSUE THREAD

**Issue by mathmaniac43** [snowzach/doods#52]
Hello,

First of all, I love this tool. Very quick and easy to set up in Docker and connect to Home Assistant, with plenty of configuration options too.

I set up a security camera to send pictures of my driveway to DOODS for identification of "car". I am still trying to find a sweet spot for the threshold, but have noticed several times that there can be multiple overlapping identifications (more than one rectangle for the same car in the same single image). Is this behavior intended, and is there any potential or desire to add a setting to prevent redundant identifications?

Thanks!

**Comment by snowzach** [comment]
Usually you can fix it by tweaking the confidence values. Sometimes it's just unavoidable though. The models actually provide many detections and they are filtered out by confidence. Usually only one box will have a good score. You could also try using a different model though as well and see where you end up.

**Comment by mathmaniac43** [comment]
Thanks, I will keep fiddling.
