### ISSUE TITLE
Label variable in DOODS intergration doco for HA

### ISSUE THREAD

**Issue by allenrong88** [snowzach/doods#55]
HA doco for DOODS:
https://www.home-assistant.io/integrations/doods/

Tried utilizing DOODS on my HA instances, worked so far without adding label variable. When I looked at the doco for label variable in order to reduce detected object to save some resources, I thought there was a bit misleading on the following highlighted area.

![image](https://user-images.githubusercontent.com/24927240/105789482-a0c77b80-5fd6-11eb-85c6-d24dc43a3924.png)

I was expecting the following code in stead of the one shown in the sample configuration. Would you be able to confirm it please?

- name: person
- name: car
- name: truck

If that's the case, would you be able to update the doco to reduce confusion in the future? 

Thx so much for this amazing project. Love it!

**Comment by snowzach** [comment]
I will try to update that in the future. Their documentation system doesn't allow you to specify the the formats that doods will take. this is basically the format that tensorflow takes also.

**Comment by allenrong88** [comment]
Thx for for your reply, really nice integration.

So I just would like to get my head clear about the correct format of the code I will be using in my HA. I will put the below code into my config, is that correct?

labels:
  - name: person
    confidence:40
  - name: car
  - name: truck

Thank you again

**Comment by snowzach** [comment]
That should actually work fine...

**Comment by allenrong88** [comment]
Thx Zach, and I will put my code above into HA config to see how it goes.
