### ISSUE TITLE
Dog detected as a person 

### ISSUE THREAD

**Issue by anubisg1** [snowzach/doods#59]
![czrsc_lan_cam01_latest](https://user-images.githubusercontent.com/4518931/107890301-6b001d80-6f18-11eb-8738-6f4dad8194b8.jpg)

As per image, I configured doods to detect people only but as you can see in the picture, my dog is detected as a person with 50% probability

**Comment by snowzach** [comment]
You just need to increase the confidence. DOODS is working properly, the model is just not accurate enough.
