### ISSUE TITLE
coral usb accelerator

### ISSUE THREAD

**Issue by allenrong88** [snowzach/doods#62]
Hi Zach,

I have been running DOODS as Hassio add-on on my raspi 4 for a while now, it works perfectly but a bit slow, which leads me to think of getting a coral usb accelerator. Can I use it or does it help and is there any additional config needed if it does?

Really appreciate your excellent work.

Thank you

**Comment by snowzach** [comment]
It's a trade off.. You can use the EdgeTPU but you must use the TFLite models which have much lower accuracy. So, trade speed for accuracy.
