### ISSUE TITLE
Run with Jetson Nano and got platform error

### ISSUE THREAD

**Issue by paisitw** [snowzach/doods#64]
I have run the below command with my Jetson Nano. What cause the error?

My environment is 
Linux JetsonNano 4.9.201-tegra #1 SMP PREEMPT Wed May 5 09:31:36 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux

$ sudo docker run -it --gpus all -p 8080:8080 snowzach/doods:cuda
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #0:: error running hook: exit status 1, stdout: src: /usr/lib/aarch64-linux-gnu/libcublasLt.so, src_lnk: libcublasLt.so.10, dst: /var/lib/docker/overlay2/7c5d5647f783b9f9507cf1392137bfe6ba2c688c62a5c241a9ff210500bcadb5/merged/usr/lib/aarch64-linux-gnu/libcublasLt.so, dst_lnk: libcublasLt.so.10

...
..
...

**Comment by snowzach** [comment]
Check this comment: https://github.com/snowzach/doods/issues/25#issuecomment-750016888
The cuda image is designed for x86 and the Nano is based on Arm. You need to build a custom image for it to work. Someone did that.

**Comment by snowzach** [comment]
Closing for now. Open an issue in the new repo if there's still issues. https://github.com/snowzach/doods2
