### ISSUE TITLE
Detecting Eggs

### ISSUE THREAD

**Issue by Bredin76** [snowzach/doods#65]
Hi, 

I'm totally a newbie in image detection and found doods for using it in home assistant as a add on.
It works really well - thanks to your work. 

My use case is to detect eggs and chicken in a chicken coop. Chicken are detected as bird in default config - its ok !
But "Egg" is not an effective target and it's the main purpose of my usecase... ( being notified when there is egg in the coop)

Can you please give me any path towards a solution ? 
I've read something about "learning" but it looks pretty hard for me. Anything else ? 

Thank a lot for your help

**Comment by snowzach** [comment]
I've started working on a new version of DOODS that will be in python and work with the object detection API. You should be able to train that a lot easier. Not sure when it will be done.

**Comment by Bredin76** [comment]
Hi,
Effectively, a method much easier for training should be very helpful for newbie like i am. 
I found someone who publish a thesis on a goal very close of mine.
I think i understand he succeed in training an egg detector based on TensorFlow : https://github.com/havluj/EggDetector

Do you thnik something in that github could be useful for my case ? like https://github.com/havluj/EggDetector/tree/master/src/impl/object-detection-training/training

despite of the difficulties in there a recipe in training ?

Regards

**Comment by sempixel** [comment]
@snowzach Any news about upcoming version? Thanks.

**Comment by snowzach** [comment]
Perhaps over the holidays I can work on this... I do want to finish that.

**Comment by snowzach** [comment]
It's complete: https://github.com/snowzach/doods2

**Comment by snowzach** [comment]
Re-Open the issue in the new repo if you are unable to get it to work.

**Comment by Clubeddie** [comment]
> Hi, Effectively, a method much easier for training should be very helpful for newbie like i am. I found someone who publish a thesis on a goal very close of mine. I think i understand he succeed in training an egg detector based on TensorFlow : https://github.com/havluj/EggDetector
> 
> Do you thnik something in that github could be useful for my case ? like https://github.com/havluj/EggDetector/tree/master/src/impl/object-detection-training/training
> 
> despite of the difficulties in there a recipe in training ?
> 
> Regards

@Bredin76 I am searching today for the same solution. I only started with doods2, did you find a solution for this?
