### ISSUE TITLE
Green and glitches

### ISSUE THREAD

**Issue by jannecklarsson** [snowzach/doods#66]
I sometimes get green color and glitches in the scanned image. This resulting in wrongful detection of objects. 

HA 2021.8.4
Hass.io on rpi 3b+

**Comment by snowzach** [comment]
That's really somewhere between Hass.IO and your camera. Hass collects the images and then sends them to Doods. If it's green or distorted, it's probably someething to do with your camera or the camera sensor in Hass.

**Comment by jannecklarsson** [comment]
Thanx!
