### ISSUE TITLE
dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: 

### ISSUE THREAD

**Issue by arfrater** [snowzach/doods#71]
cannot find how to resolve issue ??
Debian 10 shows file location /usr/lib/x86_64-linux-gnu/nvidia/current/libcuda.so.1 and /var/lib/docker/overlay2/a19ab8cf70012a1362100ae1a4636a8a9fdba53753a861229e5631cbf868b701/diff/usr/local/cuda-10.2/compat/libcuda.so.1

**Comment by snowzach** [comment]
One of them is inside of the container and one of them is outside of the container. You could try setting `LD_LIBRARY_PATH=/usr/local/cuda-10.2/compat` in the environment in the container. That might do it.

**Comment by arfrater** [comment]
Going to sound really stupid here but how to set LD_LIBRARY_PATH

**Comment by snowzach** [comment]
Are you running it in docker? If so, you can try adding `-e LD_LIBRARY_PATH=/usr/local/cuda-10.2/compat` to the docker command.

**Comment by arfrater** [comment]
OK so I was running as the home-assistant addon changed to the docker container snowzach/doods:cuda and now only error or message is kernel version does not match DSO version is that a problem
added LD_LIBRARY_PATH=/usr/local/cuda-10.2/compat via portainer ENV and restarted

**Comment by snowzach** [comment]
I am not sure. If it works, probably not. I don't know enough about NVidia CUDA stuff.

**Comment by snowzach** [comment]
It might be that the CUDA libraries are too old. I might update the HASS io images to use DOODS2. I'v rewritten the whole thing in Python and the CUDA libraries should be up to date: https://github.com/snowzach/doods2

**Comment by snowzach** [comment]
Going to close this issue. Open a new issue in the DOODS2 repo if the issue persistes.
