### ISSUE TITLE
How could i implement my own database? 

### ISSUE THREAD

**Issue by ConstantinM2** [snowzach/doods#73]
![doods (1)](https://user-images.githubusercontent.com/77556862/162223133-50335dd8-dcc8-40e0-91bf-794dfca6aef2.jpg)
Hey,

i am using this greate AddOne on Home Assistant on my 3d Printer and i would like to scan for any print failures.
Therefore in need to implement a new Database.
I am not really a pro at docker container n stuff but is it possible?

I had the idear to upload like idk 1000 images of failed prints and use those as database.

There is an option thats call "https://www.thespaghettidetective.com" but it cost money.

Greetings
Constantin

**Comment by snowzach** [comment]
DOODS doesn't actually train any models. You need to use another tool to do that. There's examples for Tensorflow, Tensorflow Lite, PyTorch and Deepstack, any of which DOODS will support. I don't think it's super easy to do. I've never actually done it myself. Sorry, I wish there was an easy answer. I saw there was a project called PrintRite that supposedly had support for this and it looked like it was free but I couldn't find it's Tensorflow model that it supposedly used. If you can find that you should be able to plug it in or point me to a model and I can try to help you to get it working.

**Comment by ConstantinM2** [comment]
Ok, i am going to look for any possible tensorflow model or maybe create my own.
At this point i have no idear about tensorflow but the way is the goal :)
Thanks for your fast responds
